repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      # - id: ruff
      #   args: [--fix]
      #   files: (\.py|SConstruct|SCsub)$
      #   types_or: [text]
      - id: ruff-format
        args: [--line-length=190]
        files: (\.py|SConstruct|SCsub)$
        types_or: [text]
  # - repo: https://github.com/pre-commit/mirrors-clang-format
  #   rev: v20.1.7
  #   hooks:
  #     - id: clang-format
