#!/usr/bin/env python
import os

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ....godot.misc.utility.scons_hints import *

# Enable C++23
def set_cpp_standard(env):
    if not env.msvc:
        env["CXXFLAGS"].remove("-std=gnu++17")
        env["CXXFLAGS"].insert(0, "-std=c++23")
    else:
        env["CXXFLAGS"].remove("/std:c++17")
        env["CXXFLAGS"].insert(0, "/std:c++23")
        env["CXXFLAGS"].insert(0, "/Zc:preprocessor")


def enable_all_warnings(env):
    if env.debug_features:
        env.Append(
            CXXFLAGS=[
                "-Wall",
                "-Wextra",
                "-Wshadow",
                # Disable warnings from GDCLASS stuff
                "-Wno-unused-parameter",
            ]
        )

        if using_clang(env):
            env.Append(CXXFLAGS=["-glldb"])
            env.Append(
                CXXFLAGS=[
                    "-Wimplicit-fallthrough",
                    "-Wno-deprecated-volatile",
                    "-Wno-missing-field-initializers",
                ]
            )
            env.Append(CXXFLAGS=["-pedantic", "-Wno-nested-anon-types", "-Wno-gnu-anonymous-struct", "-Wno-extra-semi"])
            env.Append(CPPDEFINES=["_LIBCPP_REMOVE_TRANSITIVE_INCLUDES"])

        if using_gcc(env):
            env.Append(CXXFLAGS=["-Wno-volatile"])


def set_flecs_defines(env):
    env.Append(
        CPPDEFINES=[
            "FLECS_CUSTOM_BUILD",
            "FLECS_CPP",
            "FLECS_CPP_NO_AUTO_REGISTRATION",
            "FLECS_CPP_NO_ENUM_REFLECTION",
            # "FLECS_PARSER", "FLECS_SCRIPT",
            "FLECS_SYSTEM",
            "FLECS_TIMER",
            "FLECS_PIPELINE",
            "FLECS_META",
            "FLECS_STATS",
            "FLECS_LOG",
            "FLECS_MODULE",
        ]
    )
    if env.debug_features:
        env.Append(CPPDEFINES=["FLECS_KEEP_ASSERT", "FLECS_NO_ALWAYS_INLINE", "FLECS_REST"])


def find_cpp_files(env):
    sources = []
    for dirpath, _, _ in os.walk("."):
        cpp_files = env.Glob(os.path.join(dirpath, "*.cpp"))
        sources.extend(cpp_files)
    return env.Flatten(sources)


def using_clang(env):
    return "clang" in os.path.basename(env["CC"])


def using_gcc(env):
    return "gcc" in os.path.basename(env["CC"])


Import("env")
Import("env_modules")

# Clone module env
env_gsg = env_modules.Clone()

set_flecs_defines(env_gsg)

# Get sources
sources = find_cpp_files(env_gsg)
env_gsg.Append(CPPPATH=".")

set_cpp_standard(env_gsg)
enable_all_warnings(env_gsg)


def build():
    if using_clang(env_gsg) and ARGUMENTS.get("use_pch", "no") == "yes":
        env_gsg.Append(CXXFLAGS=["-include-pch", f"{os.path.abspath('./pch.hpp.pch')}"])

    if ARGUMENTS.get("sft_tests", "no") == "yes":
        env_gsg.Append(CPPDEFINES=["SFT_TESTS_ENABLED"])

    # Shared lib compilation
    if ARGUMENTS.get("shared_library_module", "no") == "yes":
        env_gsg.Append(CCFLAGS=["-fPIC"])
        env_gsg["LIBS"] = []
        env_gsg.Append(SHLINKFLAGS=["-z", "now"])  # make unresolved symbol linker errors crash the program immediately on startup, not when they are encountered at run time.
        env.Append(LINKFLAGS=["-rdynamic"])  # required for symbols from godot to link properly when rebuilding shared lib, see: https://stackoverflow.com/a/24016413

        shared_lib = env_gsg.SharedLibrary(target="#bin/gsg", source=sources)
        shared_lib_shim = shared_lib[0].name.rsplit(".", 1)[0]
        env.Append(LIBS=[shared_lib_shim])
        env.Append(LIBPATH=["#bin"])
    else:
        # Static compilation
        env_gsg.add_source_files(env.modules_sources, sources)


build()
