#!/usr/bin/env python

import os

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ....godot.misc.utility.scons_hints import *

Import("env")
Import("env_modules")


# Enable C++23
def set_cpp_standard(env):
    if not env.msvc:
        env["CXXFLAGS"].remove("-std=gnu++17")
        env["CXXFLAGS"].insert(0, "-std=c++23")
    else:
        env["CXXFLAGS"].remove("/std:c++17")
        env["CXXFLAGS"].insert(0, "/std:c++23")
        env["CXXFLAGS"].insert(0, "/Zc:preprocessor")


def enable_all_warnings(env):
    if env.debug_features:
        env.Append(
            CXXFLAGS=[
                "-Wall",
                "-Wextra",
                "-Wshadow",
                # Disable warnings from GDCLASS stuff
                "-Wno-unused-parameter",
            ]
        )

        if using_clang(env):
            env.Append(CXXFLAGS=["-glldb"])
            env.Append(
                CXXFLAGS=[
                    "-Wimplicit-fallthrough",
                    "-Wno-deprecated-volatile",
                    "-Wno-missing-field-initializers",
                ]
            )
            env.Append(CXXFLAGS=["-pedantic", "-Wno-nested-anon-types", "-Wno-gnu-anonymous-struct", "-Wno-extra-semi"])
            env.Append(CPPDEFINES=["_LIBCPP_REMOVE_TRANSITIVE_INCLUDES"])

        if using_gcc(env):
            env.Append(CXXFLAGS=["-Wno-volatile"])


def set_flecs_defines(env):
    env.Append(
        CPPDEFINES=[
            "FLECS_CUSTOM_BUILD",
            "FLECS_CPP",
            "FLECS_CPP_NO_AUTO_REGISTRATION",
            "FLECS_CPP_NO_ENUM_REFLECTION",
            # "FLECS_PARSER", "FLECS_SCRIPT",
            "FLECS_SYSTEM",
            "FLECS_TIMER",
            "FLECS_PIPELINE",
            "FLECS_META",
            "FLECS_STATS",
            "FLECS_LOG",
            "FLECS_MODULE",
        ]
    )
    if env.debug_features:
        env.Append(CPPDEFINES=["FLECS_KEEP_ASSERT", "FLECS_NO_ALWAYS_INLINE", "FLECS_REST"])


def using_clang(env):
    return "clang" in os.path.basename(env["CC"])


def using_gcc(env):
    return "gcc" in os.path.basename(env["CC"])


def find_flecs_header_dirs(path):
    hpp_dirs = set()
    for root, _, files in os.walk(path):
        if any(file.endswith(".h") for file in files):
            hpp_dirs.add(root)
    return list(hpp_dirs)


def build_flecs():
    env_flecs = env_modules.Clone()

    flecs_sources: list[str] = ["flecs.c"]

    set_flecs_defines(env_flecs)
    env_flecs.Append(CPPPATH=".")

    # Compile flecs.c with C99
    if not env_flecs.msvc:
        env_flecs["CFLAGS"].remove("-std=gnu17")
        env_flecs["CFLAGS"].insert(0, "-std=gnu99")
    else:
        env_flecs["CFLAGS"].remove("/std:c17")
        env_flecs["CFLAGS"].insert(0, "/std:c99")

    env_flecs.force_optimization_on_debug()
    env_flecs.disable_warnings()
    env_flecs.add_source_files(env.modules_sources, flecs_sources)


def build_module():
    # Build modules files
    env_module = env_modules.Clone()

    module_sources: list[str] = ["ecs.cpp"]

    set_cpp_standard(env_module)
    enable_all_warnings(env_module)
    set_flecs_defines(env_module)

    env_module.Append(CPPPATH=".")
    env_module.add_source_files(env.modules_sources, module_sources)


build_flecs()
build_module()
